<a href="https://colab.research.google.com/github/MicheleQGF/ProjectAllocationBudgetSynthetic/blob/main/00_Docker_Setup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Resource Allocation & Budget Analysis · Part 1: Docker + TAWOS Setup

**Part 1 of the Full Project Allocation Budget series.** This notebook documents how I set up
the data foundation: loading the TAWOS dataset (`TAWOS.sql`), a public collection of real Jira
projects, into a MySQL 8.0 container running in Docker Desktop, and connecting to it from Python.

**What this project does overall**
1. Extract the issues, sprints and change logs of 3 real Jira projects: Mule, Appcelerator Studio and Titanium Mobile Platform.
2. Treat the real assignees as the project teams and link them to a synthetic HR dataset (HRA) as stand-in employee profiles.
3. Simulate budget allocations on top of that team data.
4. Run a complete resource and cost analysis (SPI/CPI, allocation vs. spend).

**What's real and what's simulated**
- Real: issues, sprints, assignees, effort and story points (TAWOS): Repository here: `https://github.com/SOLAR-group/TAWOS`
- Synthetic: employee profiles (`[HRA](https://www.kaggle.com/datasets/ziya07/enterprise-human-resource-allocation-dataset)`), hourly rates and project budgets, according to industry standards

**Skills shown:** Docker, MySQL, SQL, Python (pandas, SQLAlchemy), data cleaning, earned value management.

**Next:** Part 2 · Extract and clean the data → Part 3 · Team seniority and HRA matching → Part 4 · Rates, EVM and budgets.

In [ ]:
import os
from pathlib import Path

# Find the path the notebook is using
user_home = Path.home()
print("Tu carpeta de usuario real es:", user_home)

Tu carpeta de usuario real es: C:\Users\PC

In [ ]:
# Change the path
nueva_ruta = r"C:\Users\PC\Documents\TAWOS"

os.chdir(nueva_ruta)

# Verify it changed
print("Ahora estás en:", os.getcwd())

Ahora estás en: C:\Users\PC\Documents\TAWOS

# 00 · Docker Setup: TAWOS database on MySQL

**Goal:** run a local MySQL 8.0 server in Docker Desktop and load the TAWOS dump
(`TAWOS.sql`) into a database called `tawos_cleaned`, so the next notebooks can query it from Python.

**Environment:** Windows, Docker Desktop, PowerShell, MySQL 8.0 image.
**Projects used later:** Mule (ID 11), Appcelerator Studio (ID 13), Titanium Mobile Platform (ID 36).

> Run the commands below in PowerShell, not in a notebook cell.

## Step 0 · Prerequisites
1. Docker Desktop installed and **running** (engine status = running).
2. `TAWOS.sql` downloaded to `C:\Users\PC\Documents\TAWOS\...` (source: <add link>).
3. Set the password once, then restart PowerShell and Jupyter:
```powershell
setx MYSQL_ROOT_PASSWORD "choose-a-password"
```
4. Smoke test:
```powershell
docker --version
docker run hello-world
```
## Step 1 · Start the MySQL container
```powershell
docker run --name tawos-mysql -e MYSQL_ROOT_PASSWORD=$env:MYSQL_ROOT_PASSWORD -p 3306:3306 -d mysql:8.0
docker ps
```
| Flag | Meaning |
|---|---|
| `--name tawos-mysql` | Name used in every later command |
| `-e MYSQL_ROOT_PASSWORD=...` | Sets the root password |
| `-p 3306:3306` | Maps container port to `localhost:3306` (what Jupyter connects to) |
| `-d` | Runs in the background |
| `mysql:8.0` | Image and version |

## Step 2 · Copy the dump in and create the database
```powershell
docker cp "C:\Users\PC\Documents\TAWOS\21308124\TAWOS.sql\TAWOS.sql" tawos-mysql:/TAWOS.sql
docker exec -i tawos-mysql mysql -uroot -p$env:MYSQL_ROOT_PASSWORD -e "CREATE DATABASE tawos_cleaned;"
docker exec -i tawos-mysql mysql -uroot -p$env:MYSQL_ROOT_PASSWORD -e "SET GLOBAL max_allowed_packet=1073741824;"
```
`max_allowed_packet` is raised to 1 GB so the large inserts in the dump don't fail.
It resets when the container restarts, which is fine because it is only needed for the import.

## Step 3 · Import the dump
```powershell
docker exec -i tawos-mysql sh -c "mysql -uroot -p$env:MYSQL_ROOT_PASSWORD tawos_cleaned < /TAWOS.sql"
```
This takes a few minutes and prints nothing when it succeeds.

## Step 4 · Verify
```powershell
docker exec -i tawos-mysql mysql -uroot -p$env:MYSQL_ROOT_PASSWORD tawos_cleaned -e "SHOW TABLES;"
docker exec -i tawos-mysql mysql -uroot -p$env:MYSQL_ROOT_PASSWORD tawos_cleaned -e "SELECT COUNT(*) FROM Issue;"
docker exec -i tawos-mysql mysql -uroot -p$env:MYSQL_ROOT_PASSWORD tawos_cleaned -e "SELECT p.name, COUNT(DISTINCT i.id) AS issue_count, COUNT(DISTINCT s.id) AS sprint_count FROM Project p JOIN Issue i ON i.project_id = p.id LEFT JOIN Sprint s ON s.project_id = p.id GROUP BY p.name ORDER BY issue_count DESC;"
```
Schema reference (saved to a text file for later):
```powershell
docker exec -i tawos-mysql mysql -uroot -p$env:MYSQL_ROOT_PASSWORD tawos_cleaned -e "DESCRIBE Issue; DESCRIBE Sprint; DESCRIBE User; DESCRIBE Project; DESCRIBE Component; DESCRIBE Version; DESCRIBE Repository; DESCRIBE Affected_Version; DESCRIBE Fix_Version; DESCRIBE Comment; DESCRIBE Change_Log; DESCRIBE Issue_Component; DESCRIBE Issue_Link;" > schema_reference.txt
```

## Step 5 · Daily use: stop, start, back up, reset
```powershell
docker stop tawos-mysql          # data is kept
docker start tawos-mysql         # needs Docker Desktop running
docker exec tawos-mysql mysqldump -uroot -p$env:MYSQL_ROOT_PASSWORD tawos_cleaned > tawos_backup.sql   # one-time safety copy
docker rm -f tawos-mysql         # ⚠ deletes the container AND its data (re-run Steps 1–3)
```

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
import os

engine = create_engine('mysql+pymysql://root:tawos123@localhost:3306/tawos_cleaned')

project_ids = (11, 13, 36)

# Create a folder for your exports
os.makedirs('tawos_data', exist_ok=True)

# Core tables with direct Project_ID
tables_direct = {
    'Project': f"SELECT * FROM Project WHERE ID IN {project_ids}",
    'Issue': f"SELECT * FROM Issue WHERE Project_ID IN {project_ids}",
    'Sprint': f"SELECT * FROM Sprint WHERE Project_ID IN {project_ids}",
    'Component': f"SELECT * FROM Component WHERE Project_ID IN {project_ids}",
    'Version': f"SELECT * FROM Version WHERE Project_ID IN {project_ids}",
}

dataframes = {}
for name, query in tables_direct.items():
    df = pd.read_sql(query, engine)
    dataframes[name] = df
    df.to_csv(f'tawos_data/{name}.csv', index=False)
    print(f"{name}: {len(df)} rows saved")

Project: 3 rows saved
Issue: 20854 rows saved
Sprint: 691 rows saved
Component: 191 rows saved
Version: 661 rows saved

## Troubleshooting
| Symptom | Cause | Fix |
|---|---|---|
| `failed to connect to the docker API ... dockerDesktopLinuxEngine` | Docker Desktop is closed | Open it and wait for "engine running" |
| `OperationalError 2003 ... localhost:3306` in Jupyter | Container stopped | `docker start tawos-mysql` |
| `container name already in use` on `docker run` | Container already exists | `docker start tawos-mysql` instead |

In [ ]:
# Get the issue IDs from the projects you already pulled
issue_ids = tuple(dataframes['Issue']['ID'].tolist())

tables_via_issue = {
    'Comment': f"SELECT * FROM Comment WHERE Issue_ID IN {issue_ids}",
    'Change_Log': f"SELECT * FROM Change_Log WHERE Issue_ID IN {issue_ids}",
    'Issue_Component': f"SELECT * FROM Issue_Component WHERE Issue_ID IN {issue_ids}",
    'Issue_Link': f"SELECT * FROM Issue_Link WHERE Issue_ID IN {issue_ids}",
    'Affected_Version': f"SELECT * FROM Affected_Version WHERE Issue_ID IN {issue_ids}",
    'Fix_Version': f"SELECT * FROM Fix_Version WHERE Issue_ID IN {issue_ids}",
}

for name, query in tables_via_issue.items():
    df = pd.read_sql(query, engine)
    dataframes[name] = df
    df.to_csv(f'tawos_data/{name}.csv', index=False)
    print(f"{name}: {len(df)} rows saved")

Comment: 44219 rows saved
Change_Log: 462429 rows saved
Issue_Component: 20467 rows saved
Issue_Link: 8384 rows saved
Affected_Version: 15918 rows saved
Fix_Version: 21671 rows saved

In [ ]:
tables_final = {
    'User': "SELECT * FROM User",  # No Project_ID filter needed - small table
    'Repository': "SELECT * FROM Repository",
}

for name, query in tables_final.items():
    df = pd.read_sql(query, engine)
    dataframes[name] = df
    df.to_csv(f'tawos_data/{name}.csv', index=False)
    print(f"{name}: {len(df)} rows saved")

User: 206162 rows saved
Repository: 12 rows saved

In [ ]:
# Better version - filter User to your projects only
user_query = f"SELECT * FROM User WHERE Project_ID IN {project_ids}"
user_df = pd.read_sql(user_query, engine)
user_df.to_csv('tawos_data/User.csv', index=False)
print(f"User: {len(user_df)} rows saved")

# Repository - check if it links to Project first
repo_df = pd.read_sql("SELECT * FROM Repository", engine)
repo_df.to_csv('tawos_data/Repository.csv', index=False)
print(f"Repository: {len(repo_df)} rows saved")

User: 2524 rows saved
Repository: 12 rows saved

## Part 2 · Extract and clean the data ##

In [ ]:
#Explore everything

folder = 'tawos_data'
files = [f for f in os.listdir(folder) if f.endswith('.csv')]

def explore_csv(filepath, filename):
    df = pd.read_csv(filepath)

    print(f"\n{'='*70}")
    print(f"📄 {filename}")
    print(f"{'='*70}")

    # Shape
    print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")

    # Head
    print(f"\n--- HEAD (first 3 rows) ---")
    print(df.head(3))

    # Info (dtypes + non-null counts)
    print(f"\n--- INFO ---")
    df.info()

    # Describe (numeric columns only)
    numeric_cols = df.select_dtypes(include='number').columns
    if len(numeric_cols) > 0:
        print(f"\n--- DESCRIBE (numeric) ---")
        print(df[numeric_cols].describe())

    # Value counts for categorical columns (only if reasonable cardinality)
    categorical_cols = df.select_dtypes(include='object').columns
    for col in categorical_cols:
        unique_count = df[col].nunique()
        if unique_count <= 20:
            print(f"\n--- VALUE COUNTS: {col} ---")
            print(df[col].value_counts())
        else:
            print(f"\n--- {col}: {unique_count} unique values (skipped, too many) ---")

    return df

# Run for all files
dataframes = {}
for file in sorted(files):
    name = file.replace('.csv', '')
    dataframes[name] = explore_csv(os.path.join(folder, file), file)

======================================================================
📄 Affected_Version.csv
======================================================================

Shape: 15918 rows × 2 columns

--- HEAD (first 3 rows) ---
   Issue_ID  Affected_Version_ID
0     38003                  897
1     38004                  899
2     38033                  897

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 15918 entries, 0 to 15917
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Issue_ID             15918 non-null  int64
 1   Affected_Version_ID  15918 non-null  int64
dtypes: int64(2)
memory usage: 248.8 KB

--- DESCRIBE (numeric) ---
            Issue_ID  Affected_Version_ID
count   15918.000000         15918.000000
mean   376621.269255          6186.246074
std     74856.014431          1141.613649
min     38003.000000           897.000000
25%    388625.250000          6333.000000
50%    392531.500000          6423.000000
75%    396880.500000          6536.000000
max    402571.000000          6651.000000

======================================================================
📄 Change_Log.csv
======================================================================

Shape: 462429 rows × 10 columns

--- HEAD (first 3 rows) ---
       ID        Field From_Value To_Value  \
0  551684      summary        NaN      NaN
1  551685  description        NaN      NaN
2  551686      summary        NaN      NaN

                                         From_String  \
0                   Documentation: No icon for macOS
1  If you look at the documentation properties th...
2                           Documentation: Fix icons

                                           To_String  Change_Type  \
0                           Documentation: Fix icons  DESCRIPTION
1  *macOS icon*\r\n\r\nIf you look at the documen...  DESCRIPTION
2                 Documentation: MacOS icons missing  DESCRIPTION

         Creation_Date  Author_ID  Issue_ID
0  2020-09-29 20:20:50     8846.0     37998
1  2020-09-29 20:20:50     8846.0     37998
2  2020-10-02 18:00:19     8847.0     37998

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 462429 entries, 0 to 462428
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   ID             462429 non-null  int64
 1   Field          462429 non-null  str
 2   From_Value     257138 non-null  str
 3   To_Value       369296 non-null  str
 4   From_String    289942 non-null  str
 5   To_String      419443 non-null  str
 6   Change_Type    462429 non-null  str
 7   Creation_Date  462429 non-null  str
 8   Author_ID      462138 non-null  float64
 9   Issue_ID       462429 non-null  int64
dtypes: float64(1), int64(2), str(7)
memory usage: 35.3 MB

--- DESCRIBE (numeric) ---
                 ID      Author_ID       Issue_ID
count  4.624290e+05  462138.000000  462429.000000
mean   6.619357e+06  137011.648832  331878.679601
std    2.788282e+06   59248.415274  135310.086156
min    5.516840e+05    8845.000000   37998.000000
25%    7.751434e+06  163669.000000  386956.000000
50%    7.867041e+06  163702.000000  393032.000000
75%    7.982710e+06  165186.000000  398421.000000
max    8.098317e+06  165816.000000  402582.000000

--- Field: 93 unique values (skipped, too many) ---

--- From_Value: 105461 unique values (skipped, too many) ---

--- To_Value: 120510 unique values (skipped, too many) ---

--- From_String: 25321 unique values (skipped, too many) ---

C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

--- To_String: 43256 unique values (skipped, too many) ---

--- VALUE COUNTS: Change_Type ---
Change_Type
OTHER          350630
STATUS          79730
PEOPLE          15453
DESCRIPTION      9957
STORY_POINT      6659
Name: count, dtype: int64

--- Creation_Date: 192019 unique values (skipped, too many) ---

======================================================================
📄 Comment.csv
======================================================================

Shape: 44219 rows × 7 columns

--- HEAD (first 3 rows) ---
      ID                                            Comment  \
0  94090  PR - https://github.com/appcelerator/titanium_...
1  94091  The current draft can be found here: https://w...
2  94092  Available under https://docs.appcelerator.com/...

                                        Comment_Text Comment_Code  \
0  "PR - https://github.com/appcelerator/titanium...          NaN
1  "The current draft can be found here: https://...          NaN
2  "Available under https://docs.appcelerator.com...          NaN

         Creation_Date  Author_ID  Issue_ID
0  2020-09-10 21:02:46     8848.0     37999
1  2020-08-12 23:40:59     8851.0     38000
2  2020-10-01 10:26:44     8851.0     38000

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 44219 entries, 0 to 44218
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             44219 non-null  int64
 1   Comment        44218 non-null  str
 2   Comment_Text   44217 non-null  str
 3   Comment_Code   1153 non-null   str
 4   Creation_Date  44219 non-null  str
 5   Author_ID      44193 non-null  float64
 6   Issue_ID       44219 non-null  int64
dtypes: float64(1), int64(2), str(4)
memory usage: 2.4 MB

--- DESCRIBE (numeric) ---
                 ID      Author_ID       Issue_ID
count  4.421900e+04   44193.000000   44219.000000
mean   1.080022e+06  137598.737515  334219.285217
std    4.514452e+05   59145.086681  135586.822979
min    9.409000e+04    8845.000000   37999.000000
25%    1.272550e+06  163693.000000  391033.000000
50%    1.283604e+06  164692.000000  395672.000000
75%    1.294666e+06  165280.000000  399134.000000
max    1.305720e+06  165819.000000  402576.000000

--- Comment: 39253 unique values (skipped, too many) ---

--- Comment_Text: 39249 unique values (skipped, too many) ---

--- Comment_Code: 1141 unique values (skipped, too many) ---

--- Creation_Date: 43422 unique values (skipped, too many) ---

======================================================================
📄 Component.csv
======================================================================

Shape: 191 rows × 5 columns

--- HEAD (first 3 rows) ---
    ID  Jira_ID     Name                           Description  Project_ID
0  380    11903   APIDoc                              YML Docs          11
1  381    11904   Guides     Tutorials and Guide in Confluence          11
2  382    12615  Tooling  DocTool/JSDuck/TiMobile Python Tools          11

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 191 entries, 0 to 190
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           191 non-null    int64
 1   Jira_ID      191 non-null    int64
 2   Name         191 non-null    str
 3   Description  64 non-null     str
 4   Project_ID   191 non-null    int64
dtypes: int64(3), str(2)
memory usage: 7.6 KB

--- DESCRIBE (numeric) ---
                ID       Jira_ID  Project_ID
count   191.000000    191.000000  191.000000
mean   1867.151832  12948.539267   28.471204
std     273.274208   3281.447710   10.893647
min     380.000000  10000.000000   11.000000
25%    1864.500000  10233.500000   13.000000
50%    1912.000000  11707.000000   36.000000
75%    1960.500000  15058.500000   36.000000
max    2008.000000  23325.000000   36.000000

--- Name: 186 unique values (skipped, too many) ---

--- Description: 64 unique values (skipped, too many) ---

======================================================================
📄 Fix_Version.csv
======================================================================

Shape: 21671 rows × 2 columns

--- HEAD (first 3 rows) ---
   Issue_ID  Fix_Version_ID
0     38003             898
1     38016             900
2     38017             901

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 21671 entries, 0 to 21670
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Issue_ID        21671 non-null  int64
 1   Fix_Version_ID  21671 non-null  int64
dtypes: int64(2)
memory usage: 338.7 KB

--- DESCRIBE (numeric) ---
            Issue_ID  Fix_Version_ID
count   21671.000000    21671.000000
mean   341263.132758     5646.426099
std    125791.297013     1925.981483
min     38003.000000      897.000000
25%    386773.000000     6278.000000
50%    391778.000000     6392.000000
75%    398369.000000     6550.000000
max    402577.000000     6651.000000

C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns
C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

======================================================================
📄 Issue.csv
======================================================================

Shape: 20854 rows × 30 columns

--- HEAD (first 3 rows) ---
      ID  Jira_ID   Issue_Key  \
0  37998   175576  TIDOC-3403
1  37999   175527  TIDOC-3401
2  38000   175423  TIDOC-3400

                                                 URL  \
0  https://jira.appcelerator.org/rest/api/2/issue...
1  https://jira.appcelerator.org/rest/api/2/issue...
2  https://jira.appcelerator.org/rest/api/2/issue...

                                               Title  \
0               "Documentation: MacOS icons missing"
1  "Use actual constants instead of wildcard cons...
2                   "Webpack: Getting started guide"

                                         Description  \
0  "*macOS icon*    If you look at the documentat...
1  "In  document for property  [accuracy|https://...
2  "The new webpack support needs an official get...

                                    Description_Text  \
0  """*macOS icon*    If you look at the document...
1  """In  document for property  [accuracy|https:...
2  """The new webpack support needs an official g...

                                    Description_Code         Type Priority  \
0  "  #appc-docs-search .platform-icon-search {  ...  Improvement      NaN
1                                                NaN          Bug     High
2                                                NaN        Story      NaN

   ... Resolution_Time_Minutes Title_Changed_After_Estimation  \
0  ...                     0.0                              1
1  ...                   139.0                              0
2  ...                 74638.0                              0

  Description_Changed_After_Estimation Story_Point_Changed_After_Estimation  \
0                                    0                                    0
1                                    0                                    0
2                                    0                                    0

  Pull_Request_URL Creator_ID  Reporter_ID  Assignee_ID  Project_ID  Sprint_ID
0              NaN     8846.0         8846       8845.0          11        NaN
1              NaN     8848.0         8848       8848.0          11        NaN
2              NaN     8851.0         8851       8851.0          11        NaN

[3 rows x 30 columns]

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 20854 entries, 0 to 20853
Data columns (total 30 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   ID                                    20854 non-null  int64
 1   Jira_ID                               20854 non-null  int64
 2   Issue_Key                             20854 non-null  str
 3   URL                                   20854 non-null  str
 4   Title                                 20854 non-null  str
 5   Description                           20102 non-null  str
 6   Description_Text                      20102 non-null  str
 7   Description_Code                      2265 non-null   str
 8   Type                                  20854 non-null  str
 9   Priority                              20205 non-null  str
 10  Status                                20854 non-null  str
 11  Resolution                            19219 non-null  str
 12  Creation_Date                         20854 non-null  str
 13  Estimation_Date                       8873 non-null   str
 14  Resolution_Date                       19218 non-null  str
 15  Last_Updated                          20854 non-null  str
 16  Story_Point                           8873 non-null   float64
 17  Timespent                             853 non-null    float64
 18  In_Progress_Minutes                   20854 non-null  float64
 19  Total_Effort_Minutes                  20854 non-null  float64
 20  Resolution_Time_Minutes               20854 non-null  float64
 21  Title_Changed_After_Estimation        20854 non-null  int64
 22  Description_Changed_After_Estimation  20854 non-null  int64
 23  Story_Point_Changed_After_Estimation  20854 non-null  int64
 24  Pull_Request_URL                      0 non-null      float64
 25  Creator_ID                            20851 non-null  float64
 26  Reporter_ID                           20854 non-null  int64
 27  Assignee_ID                           18987 non-null  float64
 28  Project_ID                            20854 non-null  int64
 29  Sprint_ID                             6181 non-null   float64
dtypes: float64(9), int64(7), str(14)
memory usage: 4.8 MB

--- DESCRIBE (numeric) ---
                  ID        Jira_ID  Story_Point     Timespent  \
count   20854.000000   20854.000000  8873.000000    853.000000
mean   341733.673923   88738.603242     4.864927    298.263775
std    125391.502538   51234.263379     4.497324    585.729684
min     37998.000000   10000.000000     0.000000      0.000000
25%    386940.250000   33670.750000     2.000000     40.000000
50%    392153.500000   99342.500000     4.000000    120.000000
75%    397368.750000  128201.500000     8.000000    360.000000
max    402582.000000  322402.000000   144.000000  11040.000000

       In_Progress_Minutes  Total_Effort_Minutes  Resolution_Time_Minutes  \
count         2.085400e+04          2.085400e+04             2.085400e+04
mean          6.157800e+03          7.155485e+03             3.207466e+05
std           5.860626e+04          6.122670e+04             7.613657e+05
min           0.000000e+00          0.000000e+00             0.000000e+00
25%           0.000000e+00          0.000000e+00             1.725250e+03
50%           0.000000e+00          0.000000e+00             2.321350e+04
75%           6.012500e+02          1.193750e+03             2.057612e+05
max           4.417718e+06          4.417718e+06             6.133229e+06

       Title_Changed_After_Estimation  Description_Changed_After_Estimation  \
count                    20854.000000                               20854.0
mean                         0.151626                                   0.0
std                          0.358666                                   0.0
min                          0.000000                                   0.0
25%                          0.000000                                   0.0
50%                          0.000000                                   0.0
75%                          0.000000                                   0.0
max                          1.000000                                   0.0

       Story_Point_Changed_After_Estimation  Pull_Request_URL     Creator_ID  \
count                          20854.000000               0.0   20851.000000
mean                               0.048144               NaN  141643.833341
std                                0.214076               NaN   55012.856207
min                                0.000000               NaN    8845.000000
25%                                0.000000               NaN  163671.000000
50%                                0.000000               NaN  164082.000000
75%                                0.000000               NaN  165178.000000
max                                1.000000               NaN  165819.000000

         Reporter_ID    Assignee_ID    Project_ID    Sprint_ID
count   20854.000000   18987.000000  20854.000000  6181.000000
mean   141646.789777  139473.182967     25.738563  3824.555088
std     55009.398688   57074.909289     11.749762  1297.234407
min      8845.000000    8845.000000     11.000000   861.000000
25%    163671.000000  163669.000000     13.000000  4240.000000
50%    164082.000000  163962.000000     36.000000  4342.000000
75%    165178.000000  165186.000000     36.000000  4470.000000
max    165819.000000  165814.000000     36.000000  4668.000000

--- Issue_Key: 20854 unique values (skipped, too many) ---

--- URL: 20854 unique values (skipped, too many) ---

--- Title: 20746 unique values (skipped, too many) ---

--- Description: 19846 unique values (skipped, too many) ---

--- Description_Text: 19809 unique values (skipped, too many) ---

--- Description_Code: 2235 unique values (skipped, too many) ---

--- VALUE COUNTS: Type ---
Type
Bug                    10220
Enhancement Request     3126
Task                    2815
Improvement             1677
Story                   1466
New Feature              699
Sub-task                 416
Technical task           283
Epic                     152
Name: count, dtype: int64

--- VALUE COUNTS: Priority ---
Priority
Major             4532
High              3453
Critical          3101
Medium            2421
Minor             1908
To be reviewed    1601
Low               1536
Blocker           1223
Trivial            430
Name: count, dtype: int64

--- VALUE COUNTS: Status ---
Status
Closed         15425
Done            2981
Open            1264
Resolved         813
New              280
Reopened          45
In Progress       39
In Review          7
Name: count, dtype: int64

--- VALUE COUNTS: Resolution ---
Resolution
Fixed                       12013
Won't Fix or Usage Issue     2073
Completed                    1109
Duplicate                    1093
Done                          807
Cannot Reproduce              520
Invalid                       435
Won't Do                      362
Won't Fix                     360
Incomplete                    177
Needs more info                99
Not Our Bug                    73
Hold                           52
Works as Designed              31
Rejected                        9
Abandoned                       5
Declined                        1
Name: count, dtype: int64

--- Creation_Date: 20780 unique values (skipped, too many) ---

--- Estimation_Date: 8842 unique values (skipped, too many) ---

--- Resolution_Date: 18618 unique values (skipped, too many) ---

--- Last_Updated: 15321 unique values (skipped, too many) ---

======================================================================
📄 Issue_Component.csv
======================================================================

Shape: 20467 rows × 2 columns

--- HEAD (first 3 rows) ---
   Issue_ID  Component_ID
0     38002           380
1     38002           381
2     38003           380

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 20467 entries, 0 to 20466
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Issue_ID      20467 non-null  int64
 1   Component_ID  20467 non-null  int64
dtypes: int64(2)
memory usage: 319.9 KB

--- DESCRIBE (numeric) ---
            Issue_ID  Component_ID
count   20467.000000  20467.000000
mean   343417.285289   1685.691308
std    123935.324596    534.447675
min     38002.000000    380.000000
25%    387509.500000   1834.000000
50%    392657.000000   1872.000000
75%    397490.500000   1957.000000
max    402582.000000   2008.000000

======================================================================
📄 Issue_Link.csv
======================================================================

Shape: 8384 rows × 6 columns

--- HEAD (first 3 rows) ---
      ID  Issue_ID     Name Description Direction  Target_Issue_ID
0  25503    384787  Related  relates to   INBOUND           384788
1  25504    384788  Related  relates to  OUTBOUND           384787
2  25505    384792  Related  relates to  OUTBOUND           385719

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 8384 entries, 0 to 8383
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               8384 non-null   int64
 1   Issue_ID         8384 non-null   int64
 2   Name             8384 non-null   str
 3   Description      8384 non-null   str
 4   Direction        8384 non-null   str
 5   Target_Issue_ID  8384 non-null   int64
dtypes: int64(3), str(3)
memory usage: 393.1 KB

--- DESCRIBE (numeric) ---
                  ID       Issue_ID  Target_Issue_ID
count    8384.000000    8384.000000      8384.000000
mean    73111.307848  365675.704795    365675.704795
std     39404.354335   99285.511791     99285.511791
min     25503.000000   38036.000000     38036.000000
25%     28465.750000  390224.000000    390224.000000
50%    100804.500000  395887.000000    395887.000000
75%    108524.250000  399910.000000    399910.000000
max    110870.000000  402577.000000    402577.000000

--- VALUE COUNTS: Name ---
Name
Relates                 2676
Related                 1944
Duplicate               1478
Block                    780
Cloners                  560
Epic Story               336
Blocks                   258
Includes                 148
Depends                  102
Gantt: start-finish       62
Gantt: finish-start       20
Problem/Incident          14
Gantt: finish-finish       6
Name: count, dtype: int64

--- VALUE COUNTS: Description ---
Description
relates to                          4620
is duplicated by                     739
duplicates                           739
is blocked by                        519
blocks                               519
is cloned from                       280
is cloned into                       280
is a piece of                        168
is broken down into                  168
is included by                        74
includes                              74
depends on                            51
is dependent of                       51
is triggered by                       31
is triggering                         31
has to be done before                 10
has to be done after                  10
is caused by                           7
causes                                 7
has to be finished together with       6
Name: count, dtype: int64

--- VALUE COUNTS: Direction ---
Direction
INBOUND     4192
OUTBOUND    4192
Name: count, dtype: int64

======================================================================
📄 Project.csv
======================================================================

Shape: 3 rows × 9 columns

--- HEAD (first 3 rows) ---
   ID Project_Key                      Name  \
0  11       TIDOC  Titanium Mobile Platform
1  13      TISTUD       Appcelerator Studio
2  36        MULE                      Mule

                                              URL  \
0   https://jira.appcelerator.org/projects/TIDOC/
1  https://jira.appcelerator.org/projects/TISTUD/
2    https://www.mulesoft.org/jira/projects/MULE/

                                         Description           Start_Date  \
0  Titanium Mobile is a mature platform for devel...  2011-04-15 03:34:53
1  Appcelerator Studio (TISTUD) Appcelerator Stud...  2011-03-01 11:50:44
2  Mule is a lightweight enterprise service bus (...  2004-03-23 02:49:11

      Last_Update_Date        SP_Field_ID  Repository_ID
0  2020-10-08 03:22:02  customfield_10003              4
1  2020-10-21 15:05:09  customfield_10003              4
2  2020-10-22 17:14:18  customfield_10203             11

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                3 non-null      int64
 1   Project_Key       3 non-null      str
 2   Name              3 non-null      str
 3   URL               3 non-null      str
 4   Description       3 non-null      str
 5   Start_Date        3 non-null      str
 6   Last_Update_Date  3 non-null      str
 7   SP_Field_ID       3 non-null      str
 8   Repository_ID     3 non-null      int64
dtypes: int64(2), str(7)
memory usage: 348.0 bytes

--- DESCRIBE (numeric) ---
              ID  Repository_ID
count   3.000000       3.000000
mean   20.000000       6.333333
std    13.892444       4.041452
min    11.000000       4.000000
25%    12.000000       4.000000
50%    13.000000       4.000000
75%    24.500000       7.500000
max    36.000000      11.000000

--- VALUE COUNTS: Project_Key ---
Project_Key
TIDOC     1
TISTUD    1
MULE      1
Name: count, dtype: int64

--- VALUE COUNTS: Name ---
Name
Titanium Mobile Platform    1
Appcelerator Studio         1
Mule                        1
Name: count, dtype: int64

--- VALUE COUNTS: URL ---
URL
https://jira.appcelerator.org/projects/TIDOC/     1
https://jira.appcelerator.org/projects/TISTUD/    1
https://www.mulesoft.org/jira/projects/MULE/      1
Name: count, dtype: int64

--- VALUE COUNTS: Description ---
Description
Titanium Mobile is a mature platform for developers to build completely native cross-platform mobile applications.                                                                                                                 1
Appcelerator Studio (TISTUD) Appcelerator Studio is an eclipse based IDE that provides a single, extensible environment to rapidly build, test, package, and publish mobile apps across multiple devices and OSs.                  1
Mule is a lightweight enterprise service bus (ESB) and integration framework\nprovided by MuleSoft. The platform is Java-based, but can broker interactions between other platforms such as .NET using web services or sockets.    1
Name: count, dtype: int64

--- VALUE COUNTS: Start_Date ---
Start_Date
2011-04-15 03:34:53    1
2011-03-01 11:50:44    1
2004-03-23 02:49:11    1
Name: count, dtype: int64

--- VALUE COUNTS: Last_Update_Date ---
Last_Update_Date
2020-10-08 03:22:02    1
2020-10-21 15:05:09    1
2020-10-22 17:14:18    1
Name: count, dtype: int64

--- VALUE COUNTS: SP_Field_ID ---
SP_Field_ID
customfield_10003    2
customfield_10203    1
Name: count, dtype: int64

======================================================================
📄 Repository.csv
======================================================================

Shape: 12 rows × 4 columns

--- HEAD (first 3 rows) ---
   ID      Name                                        Description  \
0   1    Spring  The Spring Framework is an application framewo...
1   2  Sonatype                                                NaN
2   3    Apache                                                NaN

                            URL
0       https://jira.spring.io/
1  https://issues.sonatype.org/
2    https://issues.apache.org/

--- INFO ---
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ID           12 non-null     int64
 1   Name         12 non-null     str
 2   Description  3 non-null      str
 3   URL          12 non-null     str
dtypes: int64(1), str(3)
memory usage: 516.0 bytes

--- DESCRIBE (numeric) ---
              ID
count  12.000000
mean    6.583333
std     3.752777
min     1.000000
25%     3.750000
50%     6.500000
75%     9.250000
max    13.000000

--- VALUE COUNTS: Name ---
Name
Spring          1
Sonatype        1
Apache          1
Appcelerator    1
Atlassian       1
Hyperledger     1
Lsstcorp        1
Lyrasis         1
MongoDB         1
Moodle          1
Mulesoft        1
DNNTracker      1
Name: count, dtype: int64

--- VALUE COUNTS: Description ---
Description
The Spring Framework is an application framework and inversion of control container for the Java platform. The framework's core features can be used by any Java application, but there are extensions for building web applications on top of the Java EE (Enterprise Edition) platform.     1
DuraSpace                                                                                                                                                                                                                                                                                     1
MongoDB is a cross-platform document-oriented database pro- gram. Classified as a NoSQL database program, MongoDB uses JSON-like documents with schema.                                                                                                                                       1

C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns
C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns
C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns
C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns
C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns
C:\Users\PC\AppData\Local\Temp\ipykernel_25268\2081184453.py:31: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

In [ ]:
#Join everything into a single data set
# Start with Issue as the base (one row = one issue)
main = dataframes['Issue'].copy()

# Join Sprint info (sprint name, state, dates)
sprint_cols = dataframes['Sprint'][['ID', 'Name', 'State', 'Start_Date', 'End_Date']].rename(
    columns={'ID': 'Sprint_ID', 'Name': 'Sprint_Name', 'State': 'Sprint_State',
             'Start_Date': 'Sprint_Start', 'End_Date': 'Sprint_End'}
)
main = main.merge(sprint_cols, on='Sprint_ID', how='left')

# Join Project info (project name)
project_cols = dataframes['Project'][['ID', 'Name']].rename(
    columns={'ID': 'Project_ID', 'Name': 'Project_Name'}
)
main = main.merge(project_cols, on='Project_ID', how='left')

print(main.shape)
main.head()

(20854, 35)

,ID,Jira_ID,Issue_Key,URL,Title,Description,Description_Text,Description_Code,Type,Priority,...,Creator_ID,Reporter_ID,Assignee_ID,Project_ID,Sprint_ID,Sprint_Name,Sprint_State,Sprint_Start,Sprint_End,Project_Name
0,37998,175576,TIDOC-3403,https://jira.appcelerator.org/rest/api/2/issue...,"""Documentation: MacOS icons missing""","""*macOS icon* If you look at the documentat...","""""""*macOS icon* If you look at the document...",""" #appc-docs-search .platform-icon-search { ...",Improvement,NaN,...,8846.0,8846,8845.0,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform
1,37999,175527,TIDOC-3401,https://jira.appcelerator.org/rest/api/2/issue...,"""Use actual constants instead of wildcard cons...","""In document for property [accuracy|https://...","""""""In document for property [accuracy|https:...",NaN,Bug,High,...,8848.0,8848,8848.0,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform
2,38000,175423,TIDOC-3400,https://jira.appcelerator.org/rest/api/2/issue...,"""Webpack: Getting started guide""","""The new webpack support needs an official get...","""""""The new webpack support needs an official g...",NaN,Story,NaN,...,8851.0,8851,8851.0,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform
3,38001,175026,TIDOC-3399,https://jira.appcelerator.org/rest/api/2/issue...,"""Remove references to """"support@appcelerator.c...","""As the """"<EMAIL>"""" email address is no longer...","""""""As the """"""""<EMAIL>"""""""" email address is no ...",NaN,Story,NaN,...,8845.0,8845,8845.0,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform
4,38002,174862,TIDOC-3398,https://jira.appcelerator.org/rest/api/2/issue...,"""Document iOS showInForeground push property""","""We currently support setting {{showInForegrou...","""""""We currently support setting {{showInForegr...",""" { """"""""alert"""""""": """"""""This will show wh...",Story,NaN,...,8852.0,8852,NaN,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform

In [ ]:
# Count comments per issue
comment_counts = dataframes['Comment'].groupby('Issue_ID').size().reset_index(name='Comment_Count')
main = main.merge(comment_counts, left_on='ID', right_on='Issue_ID', how='left', suffixes=('', '_c'))
main['Comment_Count'] = main['Comment_Count'].fillna(0).astype(int)

# Count components per issue
component_counts = dataframes['Issue_Component'].groupby('Issue_ID').size().reset_index(name='Component_Count')
main = main.merge(component_counts, left_on='ID', right_on='Issue_ID', how='left', suffixes=('', '_comp'))
main['Component_Count'] = main['Component_Count'].fillna(0).astype(int)

# Count links (blocks, relates to, etc.) per issue
link_counts = dataframes['Issue_Link'].groupby('Issue_ID').size().reset_index(name='Link_Count')
main = main.merge(link_counts, left_on='ID', right_on='Issue_ID', how='left', suffixes=('', '_link'))
main['Link_Count'] = main['Link_Count'].fillna(0).astype(int)

# Clean up duplicate Issue_ID columns from merges
main = main.drop(columns=[c for c in main.columns if c.endswith(('_c', '_comp', '_link'))])

print(main.shape)

(20854, 39)

In [ ]:
main.to_csv('tawos_data/projects_dataset.csv', index=False)
print(f"Final dataset: {main.shape[0]} rows × {main.shape[1]} columns")

Final dataset: 20854 rows × 39 columns

In [ ]:
main = dataframes['Issue'].copy()

sprint_cols = dataframes['Sprint'][['ID', 'Name', 'State', 'Start_Date', 'End_Date']].rename(
    columns={'ID': 'Sprint_ID', 'Name': 'Sprint_Name', 'State': 'Sprint_State',
             'Start_Date': 'Sprint_Start', 'End_Date': 'Sprint_End'}
)
main = main.merge(sprint_cols, on='Sprint_ID', how='left')

project_cols = dataframes['Project'][['ID', 'Name']].rename(
    columns={'ID': 'Project_ID', 'Name': 'Project_Name'}
)
main = main.merge(project_cols, on='Project_ID', how='left')

comment_counts = dataframes['Comment'].groupby('Issue_ID').size().reset_index(name='Comment_Count')
main = main.merge(comment_counts, left_on='ID', right_on='Issue_ID', how='left', suffixes=('', '_c'))
main['Comment_Count'] = main['Comment_Count'].fillna(0).astype(int)

component_counts = dataframes['Issue_Component'].groupby('Issue_ID').size().reset_index(name='Component_Count')
main = main.merge(component_counts, left_on='ID', right_on='Issue_ID', how='left', suffixes=('', '_comp'))
main['Component_Count'] = main['Component_Count'].fillna(0).astype(int)

main = main.drop(columns=[c for c in main.columns if c.endswith(('_c', '_comp'))])

main.to_csv('tawos_data/projects_dataset.csv', index=False)
print(f"Final dataset: {main.shape[0]} rows × {main.shape[1]} columns")
main.head()

Final dataset: 20854 rows × 38 columns

,ID,Jira_ID,Issue_Key,URL,Title,Description,Description_Text,Description_Code,Type,Priority,...,Project_ID,Sprint_ID,Sprint_Name,Sprint_State,Sprint_Start,Sprint_End,Project_Name,Issue_ID,Comment_Count,Component_Count
0,37998,175576,TIDOC-3403,https://jira.appcelerator.org/rest/api/2/issue...,"""Documentation: MacOS icons missing""","""*macOS icon* If you look at the documentat...","""""""*macOS icon* If you look at the document...",""" #appc-docs-search .platform-icon-search { ...",Improvement,NaN,...,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform,NaN,0,0
1,37999,175527,TIDOC-3401,https://jira.appcelerator.org/rest/api/2/issue...,"""Use actual constants instead of wildcard cons...","""In document for property [accuracy|https://...","""""""In document for property [accuracy|https:...",NaN,Bug,High,...,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform,37999.0,1,0
2,38000,175423,TIDOC-3400,https://jira.appcelerator.org/rest/api/2/issue...,"""Webpack: Getting started guide""","""The new webpack support needs an official get...","""""""The new webpack support needs an official g...",NaN,Story,NaN,...,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform,38000.0,2,0
3,38001,175026,TIDOC-3399,https://jira.appcelerator.org/rest/api/2/issue...,"""Remove references to """"support@appcelerator.c...","""As the """"<EMAIL>"""" email address is no longer...","""""""As the """"""""<EMAIL>"""""""" email address is no ...",NaN,Story,NaN,...,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform,NaN,0,0
4,38002,174862,TIDOC-3398,https://jira.appcelerator.org/rest/api/2/issue...,"""Document iOS showInForeground push property""","""We currently support setting {{showInForegrou...","""""""We currently support setting {{showInForegr...",""" { """"""""alert"""""""": """"""""This will show wh...",Story,NaN,...,11,NaN,NaN,NaN,NaN,NaN,Titanium Mobile Platform,NaN,0,2

In [ ]:
main.info()

<class 'pandas.DataFrame'>
RangeIndex: 20854 entries, 0 to 20853
Data columns (total 38 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   ID                                    20854 non-null  int64
 1   Jira_ID                               20854 non-null  int64
 2   Issue_Key                             20854 non-null  str
 3   URL                                   20854 non-null  str
 4   Title                                 20854 non-null  str
 5   Description                           20102 non-null  str
 6   Description_Text                      20102 non-null  str
 7   Description_Code                      2265 non-null   str
 8   Type                                  20854 non-null  str
 9   Priority                              20205 non-null  str
 10  Status                                20854 non-null  str
 11  Resolution                            19219 non-null  str
 12  Creation_Date                         20854 non-null  str
 13  Estimation_Date                       8873 non-null   str
 14  Resolution_Date                       19218 non-null  str
 15  Last_Updated                          20854 non-null  str
 16  Story_Point                           8873 non-null   float64
 17  Timespent                             853 non-null    float64
 18  In_Progress_Minutes                   20854 non-null  float64
 19  Total_Effort_Minutes                  20854 non-null  float64
 20  Resolution_Time_Minutes               20854 non-null  float64
 21  Title_Changed_After_Estimation        20854 non-null  int64
 22  Description_Changed_After_Estimation  20854 non-null  int64
 23  Story_Point_Changed_After_Estimation  20854 non-null  int64
 24  Pull_Request_URL                      0 non-null      float64
 25  Creator_ID                            20851 non-null  float64
 26  Reporter_ID                           20854 non-null  int64
 27  Assignee_ID                           18987 non-null  float64
 28  Project_ID                            20854 non-null  int64
 29  Sprint_ID                             6181 non-null   float64
 30  Sprint_Name                           6181 non-null   str
 31  Sprint_State                          6181 non-null   str
 32  Sprint_Start                          5904 non-null   str
 33  Sprint_End                            5904 non-null   str
 34  Project_Name                          20854 non-null  str
 35  Issue_ID                              15369 non-null  float64
 36  Comment_Count                         20854 non-null  int64
 37  Component_Count                       20854 non-null  int64
dtypes: float64(10), int64(9), str(19)
memory usage: 6.0 MB

In [ ]:
main[['Creation_Date', 'Estimation_Date', 'Resolution_Date']].value_counts()

Creation_Date        Estimation_Date      Resolution_Date
2020-02-18 10:26:41  2020-02-18 10:26:41  2020-02-18 19:19:56    1
2019-09-24 17:45:17  2019-09-24 17:45:17  2019-12-02 15:59:44    1
2019-09-23 21:02:51  2019-09-23 21:02:51  2019-09-23 21:58:00    1
2019-09-16 18:55:31  2019-09-16 18:55:31  2019-09-16 20:53:23    1
2019-09-13 17:02:40  2019-09-13 17:02:40  2019-09-20 17:45:39    1
                                                                ..
2011-03-01 11:57:51  2011-03-01 11:57:51  2011-07-18 20:00:08    1
                                          2011-03-01 12:48:58    1
2011-03-01 11:56:58  2011-03-01 11:56:58  2011-03-04 17:36:21    1
2011-03-01 11:50:45  2011-03-01 11:50:45  2011-03-10 15:42:48    1
2011-03-01 11:50:44  2011-03-01 11:50:44  2018-09-13 20:47:31    1
Name: count, Length: 8475, dtype: int64

In [ ]:
#Checking for scope creep tracking accuracy
main[['Title_Changed_After_Estimation', 'Description_Changed_After_Estimation', 'Story_Point_Changed_After_Estimation']].describe()

,Title_Changed_After_Estimation,Description_Changed_After_Estimation,Story_Point_Changed_After_Estimation
count,20854.000000,20854.0,20854.000000
mean,0.151626,0.0,0.048144
std,0.358666,0.0,0.214076
min,0.000000,0.0,0.000000
25%,0.000000,0.0,0.000000
50%,0.000000,0.0,0.000000
75%,0.000000,0.0,0.000000
max,1.000000,0.0,1.000000

In [ ]:
# How many unique issues have a STORY_POINT entry in Change_Log?
sp_changes = dataframes['Change_Log'][dataframes['Change_Log']['Change_Type'] == 'STORY_POINT']
print(f"Unique issues with story point changes (from Change_Log): {sp_changes['Issue_ID'].nunique()}")

# Compare to the flag count
print(f"Issues flagged Story_Point_Changed_After_Estimation=1: {(main['Story_Point_Changed_After_Estimation']==1).sum()}")

Unique issues with story point changes (from Change_Log): 5787
Issues flagged Story_Point_Changed_After_Estimation=1: 1004

"I identified that TAWOS's derived Story_Point_Changed_After_Estimation flag undercounted actual revisions by ~83% when cross-validated against the raw Change_Log. I used Change_Log directly to build a reliable scope-creep metric instead."

In [ ]:
# Get the actual set of issues with real story point changes
issues_with_sp_changes = set(sp_changes['Issue_ID'].unique())

main['Story_Point_Revised'] = main['ID'].isin(issues_with_sp_changes).astype(int)

print(main['Story_Point_Revised'].value_counts())

Story_Point_Revised
0    15067
1     5787
Name: count, dtype: int64

In [ ]:
# How many issues have ZERO Change_Log entries at all?
issues_with_any_log = set(dataframes['Change_Log']['Issue_ID'].unique())
issues_no_log = main[~main['ID'].isin(issues_with_any_log)]

print(f"Total issues: {len(main)}")
print(f"Issues with at least one Change_Log entry: {len(issues_with_any_log)}")
print(f"Issues with ZERO Change_Log entries: {len(issues_no_log)}")

Total issues: 20854
Issues with at least one Change_Log entry: 20831
Issues with ZERO Change_Log entries: 23

Change_Log tracking mechanism = working, comprehensive (99.9% of issues have some entry)
Therefore, if an issue's story point had been revised, that specific STORY_POINT change type would very likely have been captured too
5,787 issues with story point revisions is trustworthy — the logging system was clearly active and catching changes

In [ ]:
print(main['Type'].value_counts())
print()
print(main['Priority'].value_counts())
print()
print(main['Status'].value_counts())
print()
print(main['Resolution'].value_counts())

Type
Bug                    10220
Enhancement Request     3126
Task                    2815
Improvement             1677
Story                   1466
New Feature              699
Sub-task                 416
Technical task           283
Epic                     152
Name: count, dtype: int64

Priority
Major             4532
High              3453
Critical          3101
Medium            2421
Minor             1908
To be reviewed    1601
Low               1536
Blocker           1223
Trivial            430
Name: count, dtype: int64

Status
Closed         15425
Done            2981
Open            1264
Resolved         813
New              280
Reopened          45
In Progress       39
In Review          7
Name: count, dtype: int64

Resolution
Fixed                       12013
Won't Fix or Usage Issue     2073
Completed                    1109
Duplicate                    1093
Done                          807
Cannot Reproduce              520
Invalid                       435
Won't Do                      362
Won't Fix                     360
Incomplete                    177
Needs more info                99
Not Our Bug                    73
Hold                           52
Works as Designed              31
Rejected                        9
Abandoned                       5
Declined                        1
Name: count, dtype: int64

In [ ]:
# Create a flag for whether Story_Point is missing
main['Has_Story_Point'] = main['Story_Point'].notna()

# Crosstab: Type vs whether it has a story point
pd.crosstab(main['Type'], main['Has_Story_Point'], normalize='index') * 100

Has_Story_Point          False      True
Type
Bug                  63.767123  36.232877
Enhancement Request  69.257837  30.742163
Epic                 80.263158  19.736842
Improvement          39.892665  60.107335
New Feature          43.633763  56.366237
Story                40.654843  59.345157
Sub-task             89.663462  10.336538
Task                 41.705151  58.294849
Technical task       21.201413  78.798587

In [ ]:
# Cross-check: Story_Point null vs Estimation_Date null
pd.crosstab(main['Story_Point'].isna(), main['Estimation_Date'].isna())

Estimation_Date  False  True
Story_Point
False             8873      0
True                 0  11981

In [ ]:
pd.crosstab(main['Project_Name'], main['Has_Story_Point'], normalize='index') * 100

Has_Story_Point               False      True
Project_Name
Appcelerator Studio       43.033952  56.966048
Mule                      64.708869  35.291131
Titanium Mobile Platform  57.600523  42.399477

In [ ]:
# Filter to only the issues WITHOUT a story point
no_estimate = main[main['Story_Point'].isna()]

print(no_estimate['Type'].value_counts())
print()
print((no_estimate['Type'].value_counts(normalize=True) * 100).round(1))

Type
Bug                    6517
Enhancement Request    2165
Task                   1174
Improvement             669
Story                   596
Sub-task                373
New Feature             305
Epic                    122
Technical task           60
Name: count, dtype: int64

Type
Bug                    54.4
Enhancement Request    18.1
Task                    9.8
Improvement             5.6
Story                   5.0
Sub-task                3.1
New Feature             2.5
Epic                    1.0
Technical task          0.5
Name: proportion, dtype: float64

In [ ]:
unplanned_pct = main['Story_Point'].isna().sum() / len(main) * 100
print(f"Unplanned/reactive work: {unplanned_pct:.1f}% of all issues")

# Effort spent on unplanned work (still measurable, even without story points)
unplanned_effort = main[main['Story_Point'].isna()]['Total_Effort_Minutes'].sum()
total_effort = main['Total_Effort_Minutes'].sum()
print(f"% of total effort spent on unplanned work: {unplanned_effort/total_effort*100:.1f}%")

Unplanned/reactive work: 57.5% of all issues
% of total effort spent on unplanned work: 51.8%

We will calculate the SPI/CPI based on PLANNED work, estimated and that has Story Points
The remaining 57% — largely reactive bug fixes — consumed 51.8% of total effort, representing capacity not reflected in sprint planning. This highlights a common resource-planning risk: teams may look on-schedule per SPI while unplanned work quietly erodes capacity.

In [ ]:
print(main['Sprint_Name'].value_counts())
print()
print(main['Sprint_State'].value_counts())
print()
print(main['Sprint_Start'].value_counts())
print()
print(main['Sprint_End'].value_counts())

Sprint_Name
Mule 4.5                        150
To Be Scheduled                  81
SDK 4.x                          69
Mule 4 GA Harley Quinn 10/12     62
Mule 4 Joker 10/26               60
                               ...
2017 Sprint 11 Studio             1
2016 Sprint 12 Studio             1
2015 Sprint 23 Tooling            1
2015 Sprint 18 Studio             1
Release 3.0.0                     1
Name: count, Length: 574, dtype: int64

Sprint_State
CLOSED    5903
FUTURE     277
ACTIVE       1
Name: count, dtype: int64

Sprint_Start
2016-03-28 04:03:55    81
2017-09-28 18:49:11    62
2014-05-12 16:00:00    60
2017-10-12 19:09:31    60
2013-10-21 20:22:56    56
                       ..
2017-05-22 07:25:46     1
2016-06-07 05:23:04     1
2015-11-10 23:44:28     1
2015-09-01 16:00:30     1
2012-09-27 05:26:47     1
Name: count, Length: 561, dtype: int64

Sprint_End
2016-04-08 04:03:00    81
2017-10-12 18:49:00    62
2014-05-24 00:00:00    60
2017-10-26 19:09:00    60
2013-11-03 21:23:56    56
                       ..
2018-02-26 06:12:00     1
2017-06-05 07:25:00     1
2016-06-21 05:23:00     1
2015-11-21 02:44:00     1
2012-10-08 20:05:00     1
Name: count, Length: 547, dtype: int64

In [ ]:
date_cols = ['Creation_Date', 'Estimation_Date', 'Resolution_Date', 'Last_Updated',
             'Sprint_Start', 'Sprint_End']

for col in date_cols:
    main[col] = pd.to_datetime(main[col], errors='coerce')

# Verify it worked
main[date_cols].dtypes

Creation_Date      datetime64[us]
Estimation_Date    datetime64[us]
Resolution_Date    datetime64[us]
Last_Updated       datetime64[us]
Sprint_Start       datetime64[us]
Sprint_End         datetime64[us]
dtype: object

In [ ]:
main[['Comment_Count', 'Component_Count']].describe()

       Comment_Count  Component_Count
count   20854.000000     20854.000000
mean        2.120409         0.981442
std         2.787135         0.520607
min         0.000000         0.000000
25%         0.000000         1.000000
50%         1.000000         1.000000
75%         3.000000         1.000000
max        47.000000         7.000000

In [ ]:
main[['Comment_Count', 'Resolution_Time_Minutes']].corr()

                         Comment_Count  Resolution_Time_Minutes
Comment_Count                 1.000000                 0.034223
Resolution_Time_Minutes       0.034223                 1.000000

No Correlation between Comment_Count and Resolution_Time so Comment_Count and Component_Count are just descriptive metrics (how much discussion, how cross-cutting) — useful to mention in passing, but not a hidden driver of your CPI/SPI story.

In [ ]:
main = main.drop(columns=[
    'Pull_Request_URL',
    'Description_Changed_After_Estimation',
    'Title_Changed_After_Estimation',
    'Story_Point_Changed_After_Estimation',
    'Issue_ID',  # leftover from merge
    'URL',
    'Description_Code',
    'Jira_ID'
])
print(main.shape)
main.columns.tolist()

(20854, 32)

['ID',
 'Issue_Key',
 'Title',
 'Description',
 'Description_Text',
 'Type',
 'Priority',
 'Status',
 'Resolution',
 'Creation_Date',
 'Estimation_Date',
 'Resolution_Date',
 'Last_Updated',
 'Story_Point',
 'Timespent',
 'In_Progress_Minutes',
 'Total_Effort_Minutes',
 'Resolution_Time_Minutes',
 'Creator_ID',
 'Reporter_ID',
 'Assignee_ID',
 'Project_ID',
 'Sprint_ID',
 'Sprint_Name',
 'Sprint_State',
 'Sprint_Start',
 'Sprint_End',
 'Project_Name',
 'Comment_Count',
 'Component_Count',
 'Story_Point_Revised',
 'Has_Story_Point']

In [ ]:
# Save BEFORE any HRA/rate merges, so it only holds TAWOS-derived columns
assert 'Was_Reassigned' in main.columns   # computed from Change_Log, so it must exist here
main.to_csv('tawos_data/main_part2.csv', index=False)